<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Assert.fs" />
    <Compile Include="Proc.fs" />
    <Compile Include="ExTester.fs" />
    <Compile Include="ReloadRecover.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="10.1.204" />
    <PackageReference Include="Fable.Core" Version="5.2.0" />
    <PackageReference Include="Fable.Mocha" Version="2.17.0" />
  </ItemGroup>
</Project>
